# Generated by Django 5.0.6 on 2024-07-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='auth_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('VERIFIED', 'VERIFIED'), ('DONE', 'DONE'), ('PHOTO', 'PHOTO')], default='NEW', max_length=128),
        ),
    ]
