# Generated by Django 5.0.6 on 2024-07-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='photos',
            field=models.ImageField(default='products/images.png', upload_to='products'),
        ),
    ]
